### ISSUE TITLE
[Resource Quota Lecture] All objects must use either requests or limits

### ISSUE THREAD

**Issue by abdennour** [LevelUpEducation/kubernetes-demo#19]
What happens during that lecture is we configure the limits.cpu in the Resourcequote. But don't configure it in the tomcat-deployment instead we configure the Cpu requests. 

Which occurs in the error we receive. If you change limits.cpu to requests.cpu everything works just fine.

**Related Question(s)**
- https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/questions/5088982

**Comment by abdennour** [comment]
Here two possible solutions: 

1. Using limits

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    limits.cpu: "400m"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
```

2. Using requests


```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "400m"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
```
